#spring:
#  security:
#    user:
#      name: admin
#      password: admin

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
#  设置session 超时时间
  session:
    timeout: 1m


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印日志
  type-aliases-package: com.cheng.springsecurity.entity    #配置别名
# 设置session超时时间
server:
  servlet:
    session:
      timeout: 1m
  port: 8081